Repository aleph-im/aleph-client, pull requests merged in 2024-08, with the labels that each got.

#242 Fix: revert upgrade: aiohttp 3.10.2 -> 3.9.5
  pyproject.toml
Labels: BLACK

#244 Provide a template for new PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: BLUE

#246 Fix: Cross-device links crashed 'confidential-init-session'
  src/aleph_client/commands/instance/__init__.py
Labels: BLUE

#251 Fix IPv6 in instance list + fix crash
  src/aleph_client/commands/instance/__init__.py
Labels: BLUE

#249 Update PR template with details on documentation
  .github/PULL_REQUEST_TEMPLATE.md
Labels: easy, BLUE

#254 Fix docs
  docs/content/account.rst
Labels: BLUE

#255 Confidential command: Pass hash vm_id and crn_url as argument
  src/aleph_client/commands/instance/__init__.py
Labels: BLUE
